//
//  Dairy.swift
//  Keep
//
//  Created by Luna An on 1/1/17.
//  Copyright © 2017 Mimicatcodes. All rights reserved.
//

import Foundation

var dairy = [
    
    "America cheese",
    "Bleu cheese",
    "Brie cheese",
    "Cheddar",
    "Cottage cheese",
    "Cream cheese",
    "Feta",
    "Goat cheese",
    "Mozzarella",
    "Parmesan",
    "Provolone",
    "Ricotta",
    "Firm cheese",
    "Soft cheese",
    "Sandwich slices",
    "Swiss cheese",
    "Roquefort",
    "Camembert",
    "Cotija",
    "Chèvre",
    "Emmental",
    "Gouda",
    "Goat cheese",
    "Taleggio",
    "Parmigiano-Reggiano",
    "Manchego",
    "Monterey Jack",
    "Pepper Jack",
    "Dry Jack",
    "String cheese",
    "Vegetarian cheese",
    "Whole Milk",
    "2% Fat Milk",
    "1% Fat Milk",
    "Low Fat Milk",
    "Fat-Free Milk",
    "Whole Lactose Milk",
    "2% Lactose Milk",
    "Fat-Free Lactose Milk",
    "Whole Lactose-Free Milk",
    "2% Lactose-Free Milk",
    "Nonfat Lactose-Free Milk",
    "Powdered (Dry) Milk",
    "Nonfat Powdered Milk",
    "Evaporated Milk",
    "Condensed Milk",
    "Skimmed Evaporated Milk",
    "Chocolate Flavored Milk",
    "Strawberry Flavored Milk",
    "Skim Milk",
    "Banana milk",
    "Yogurt - Whole Milk",
    "Yogurt - Low Fat",
    "Yogurt - Fat-Free",
    "Fat-Free Fruit Yogurt",
    "Greek Plain Yogurt",
    "Greek Low Fat Yogurt",
    "Greek Nonfat Yogurt",
    "Drinkable Yogurt",
    "Lowfat Drinkable Yogurt",
    "Butter - Salted",
    "Butter - Unsalted",
    "Margarine",
    "Block Butter",
    "Spreadable Butter",
    "Olive Spread",
    "Sunflower Spread",
    "Organic Butter & Spread ",
    "Flavored & Sweet Butter ",
    "Dairy Free Spread",
    "Baking Fat",
    "Cooking Fat",
    "Sour Cream",
    "Whipped Cream",
    "Ice Cream",
    "Gelato",
    "Popsicle",
    "Frozen Yogurt"
]


