//
//  Dairy.swift
//  Keep
//
//  Created by Luna An on 1/1/17.
//  Copyright © 2017 Mimicatcodes. All rights reserved.
//

import Foundation

var dairy: Set<String> = [
    
    "America Cheese",
    "Bleu Cheese",
    "Brie Cheese",
    "Cheddar Cheese",
    "Cheese",
    "Cottage Cheese",
    "Cream Cheese",
    "Feta",
    "Goat Cheese",
    "Mozzarella",
    "Parmesan",
    "Provolone",
    "Ricotta",
    "Firm Cheese",
    "Soft Cheese",
    "Sandwich Slices",
    "Swiss Cheese",
    "Roquefort",
    "Camembert",
    "Cotija",
    "Chèvre",
    "Emmental",
    "Gouda",
    "Goat Cheese",
    "Taleggio",
    "Parmigiano-Reggiano",
    "Manchego",
    "Monterey Jack",
    "Pepper Jack",
    "Dry Jack",
    "String Cheese",
    "Vegetarian Cheese",
    "Milk - Whole",
    "Milk - 2%",
    "Milk - 1%",
    "Milk - Low Fat",
    "Skim Milk",
    "Milk - Whole Lactose",
    "Lactose Milk 2%",
    "Lactose Milk Fat-Free",
    "Whole Lactose-Free Milk",
    "2% Lactose-Free Milk",
    "Nonfat Lactose-Free Milk",
    "Powdered (Dry) Milk",
    "Nonfat Powdered Milk",
    "Evaporated Milk",
    "Condensed Milk",
    "Skimmed Evaporated Milk",
    "Chocolate Flavored Milk",
    "Strawberry Flavored Milk",
    "Skim Milk",
    "Banana Milk",
    "Yogurt - Whole Milk",
    "Yogurt - Low Fat",
    "Yogurt - Fat-Free",
    "Fat-Free Fruit Yogurt",
    "Greek Plain Yogurt",
    "Greek Low Fat Yogurt",
    "Greek Nonfat Yogurt",
    "Drinkable Yogurt",
    "Lowfat Drinkable Yogurt",
    "Butter",
    "Butter - Salted",
    "Butter - Unsalted",
    "Margarine",
    "Block Butter",
    "Spreadable Butter",
    "Olive Spread",
    "Sunflower Spread",
    "Organic Butter & Spread ",
    "Flavored & Sweet Butter ",
    "Dairy Free Spread",
    "Baking Fat",
    "Cooking Fat",
    "Sour Cream",
    "Whipped Cream",
    "Ice Cream",
    "Gelato",
    "Popsicle",
    "Frozen Yogurt"
]


