//
//  FrozenFoods.swift
//  Keep
//
//  Created by Luna An on 1/1/17.
//  Copyright © 2017 Mimicatcodes. All rights reserved.
//

import Foundation


var frozenFoods = [
    
    "Frozen Corn",
    "Frozen Fish Sticks",
    "Frozen Mozzarella Sticks",
    "Frozen Fruit",
    "Frozen Lasagna",
    "Frozen Peas",
    "Frozen Vegetables",
    "Frozen Pizza",
    "Frozen Waffles",
    "Frozen Juice",
    "Frozen Asparagus",
    "Frozen Bagels",
    "Frozen Bakery",
    "Frozen Beans",
    "Frozen Burgers",
    "Frozen Meal",
    "Frozen Meat",
    "Frozen Bell Peppers",
    "Frozen Berries",
    "Frozen Banana",
    "Frozen Strawberry",
    "Frozen Mango",
    "Frozen Blueberries",
    "Frozen Blackberries",
    "Frozen Chicken",
    "Frozen Soup",
    "Frozen Bread",
    "Frozen Bread Dough",
    "Frozen Beef",
    "Frozen Pork",
    "Frozen Breakfast",
    "Frozen Lunch",
    "Frozen Indian Food",
    "Frozen Burritos",
    "Frozen Wings",
    "Frozen Broccoli",
    "Frozen Brussel Sprouts",
    "Frozen Cake",
    "Frozen Carrots",
    "Frozen Cauliflower",
    "Frozen Shrimp",
    "Frozen Calamari",
    "Frozen Cheese Sticks",
    "Frozen Cheeseburger",
    "Frozen Cherries",
    "Frozen Cinnamon Rolls",
    "Frozen Clams",
    "Frozen Cookie Dough",
    "Frozen Cookies",
    "Frozen Crab",
    "Frozen Crab Cakes",
    "Frozen Dumplings",
    "Frozen Noodle",
    "Frozen Udon Noodle",
    "Frozen Salmon",
    "Frozen White Fish",
    "Frozen Code Fish",
    "Frozen Dessert",
    "Frozen Dinner",
    "Frozen Dip",
    "Frozen Donuts",
    "Frozen Fish Fillets",
    "Frozen French Toast",
    "Frozen Garlic Bread",
    "Frozen Hash Browns",
    "Frozen Sausage",
    "Frozen Lobster",
    "Frozen Mashed Potatoes",
    "Frozen Matzah Balls",
    "Frozen Mexican",
    "Frozen Mixed Fruit",
    "Frozen Mixed Berries",
    "Frozen Meals",
    "Frozen Mushrooms",
    "Frozen Okra",
    "Frozen Omelettes",
    "Frozen Onions",
    "Frozen Pancakes",
    "Frozen Pasta",
    "Frozen Pizza Rolls",
    "Frozen Seafood",
    "Frozen Raspberries",
    "Frozen Spinach",
    "Frozen Squid",
    "Frozen Squash",
    "Frozen Tater Tots",
    "Frozen Turkey",
    "Frozen Yogurt"
    
]
