//
//  Grains.swift
//  Keep
//
//  Created by Luna An on 1/1/17.
//  Copyright © 2017 Mimicatcodes. All rights reserved.
//

import Foundation

var pastaAndNoodles: Set<String>  = [
    
    "Spaghettoni",
    "Spaghetti",
    "Spaghettini",
    "Fedelini",
    "Vermicelloni",
    "Vermicelli",
    "Capellini",
    "Capelli d'angelo",
    "Barbina",
    "Bucatini",
    "Perciatelli",
    "Fusilli lunghi",
    "Fusilli bucati",
    "Pici",
    "Soba - そば",
    "Udon - うどん",
    "Cu mian - 粗麵",
    "Ziti",
    "Zitoni",
    "Spaghetti alla chitarra",
    "Ciriole",
    "Bavette",
    "Bavettine",
    "Fettuce",
    "Fettuccine",
    "Fettucelle",
    "Lagane",
    "Lasagne",
    "Lasagnette",
    "Lasagnotte",
    "Linguettine",
    "Linguine",
    "Mafalde",
    "Mafaldine",
    "Pappardelle",
    "Pillus",
    "Pizzoccheri",
    "Sagnarelli",
    "Scialatelli",
    "Stringozzi",
    "Tagliatelle",
    "Taglierini",
    "Trenette",
    "Tripoline",
    "Shahe fen",
    "Biáng biáng noodles",
    "Calamarata",
    "Calamaretti",
    "Cannelloni",
    "Cavatappi",
    "Cellentani",
    "Chifferi",
    "Ditalini",
    "Fideuà",
    "Gomito",
    "Elicoidali",
    "Fagioloni",
    "Fusilli",
    "Garganelli",
    "Gemelli",
    "Maccheroncelli",
    "Maltagliati",
    "Manicotti",
    "Marziani",
    "Mezzani pasta",
    "Mezze penne",
    "Mezzi bombardoni",
    "Mostaccioli",
    "Paccheri",
    "Pasta al ceppo",
    "Penne",
    "Penne Rigate",
    "Penne Lisce",
    "Penne Zita",
    "Pennette",
    "Pennoni",
    "Rigatoncini",
    "Rigatoni",
    "Sagne 'Ncannulate",
    "Spirali",
    "Spiralini",
    "Trenne",
    "Trennette",
    "Tortiglioni",
    "Tuffoli",
    "Capunti",
    "Casarecce",
    "Cavatelli",
    "Cencioni",
    "Conchiglie",
    "Conchiglioni",
    "Corzetti",
    "Creste Di Galli",
    "Croxetti",
    "Farfalle",
    "Farfalloni",
    "Fiorentine",
    "Fiori",
    "Foglie D'ulivo",
    "Gigli",
    "Gramigna",
    "Lanterne",
    "Lumache",
    "Lumaconi",
    "Maltagliati",
    "Mandala",
    "Marille",
    "Orecchiette",
    "Pipe",
    "Quadrefiore",
    "Radiatori",
    "Ricciolini",
    "Ricciutelle",
    "Rotelle",
    "Rotini",
    "Strozzapreti",
    "Torchio",
    "Trofie",
    "Gnocchi",
    "Passatelli",
    "Spätzle",
    "Acini Di Pepe",
    "Bead-like Pasta",
    "Alfabeto",
    "Anelli",
    "Anellini",
    "Couscous",
    "Conchigliette",
    "Corallini",
    "Ditali",
    "Ditalini",
    "Egg barley",
    "Farfalline",
    "Fideos",
    "Filini",
    "Fregula",
    "Funghini",
    "Israeli Couscous",
    "Occhi Di Pernice",
    "Orzo",
    "Pastina",
    "Pearl Pasta",
    "Ptitim",
    "Quadrettini",
    "Risi",
    "Seme Di Melone",
    "Stelle",
    "Stelline",
    "Stortini",
    "Tarhana",
    "Agnolotti",
    "Cannelloni",
    "Casoncelli",
    "Casunziei",
    "Fagottini",
    "Maultasche",
    "Mezzelune",
    "Occhi Di Lupo",
    "Pelmeni",
    "Pierogi",
    "Macaroni",
    "Ravioli",
    "Sacchettini",
    "Sacchettoni",
    "Tortellini",
    "Tortelloni",
    "Ramen",
    "Whole Wheat Pasta",
]

var otherGrains: Set<String> = [
    
    "Amaranth",
    "Barley",
    "Brown Rice",
    "Brown Rice Bread",
    "Brown Rice Tortilla",
    "Buckwheat",
    "Bulgur (Cracked Wheat)",
    "Farro",
    "Flaxseed",
    "Grano",
    "Kamut® Grain",
    "Millet",
    "Oats",
    "Oat Bread",
    "Oat Cereal",
    "Oatmeal",
    "Popcorn",
    "Cerials",
    "Cereal Flakes",
    "Muesli",
    "Rolled Oats",
    "Quinoa",
    "Rye",
    "Sorghum",
    "Spelt",
    "Teff",
    "Triticale",
    "Wheat Berries",
    "Cornmeal",
    "Whole Rye",
    "Pita Bread",
    "Tortillas",
    "Wild Rice",
    "White Rice",
    "Baguettes",
    "Bagels",
    "Bialys",
    "Knishes",
    "Croissants",
    "Danish",
    "Pumpernickel",
    "Rye Bread",
    "Rolls & Buns",
    "Sourdough",
    "White Bread",
    "Sliced Bread",
    "Whole Wheat Bread",
    "Multigrain Bread",
    "Cake",
    "Cupcake",
    "Chocolate Treats",
    "Cookies",
    "Brownies",
    "Muffins",
    "Scones",
    "Pies",
    "Tarts",
    "Pudding",
    "Soufflé",
    "Cornbread",
    "Corn Tortillas",
    "Couscous",
    "Flour Tortillas",
    "Grits",
    "Pitas",
    "Pretzels",
    "Naan"
]


