//
//  PastaAndNoodles.swift
//  Keep
//
//  Created by Luna An on 1/1/17.
//  Copyright © 2017 Mimicatcodes. All rights reserved.
//

import Foundation

var pastaAndNoodles : [String] = [
    
    "Spaghettoni",
    "Spaghetti",
    "Spaghettini",
    "Fedelini",
    "Vermicelloni",
    "Vermicelli",
    "Capellini",
    "Capelli d'angelo",
    "Barbina",
    "Bucatini",
    "Perciatelli",
    "Fusilli lunghi",
    "Fusilli bucati",
    "Pici",
    "Soba - そば (Japanese)",
    "Udon - うどん (Japanese)",
    "Cu mian - 粗麵 (Chinese)",
    "Ziti",
    "Zitoni",
    "Spaghetti alla chitarra",
    "Ciriole",
    "Bavette",
    "Bavettine",
    "Fettuce",
    "Fettuccine",
    "Fettucelle",
    "Lagane",
    "Lasagne",
    "Lasagnette",
    "Lasagnotte",
    "Linguettine",
    "Linguine",
    "Mafalde",
    "Mafaldine",
    "Pappardelle",
    "Pillus",
    "Pizzoccheri",
    "Sagnarelli",
    "Scialatelli or scilatielli",
    "Stringozzi",
    "Tagliatelle",
    "Taglierini",
    "Trenette",
    "Tripoline",
    "Shahe fen -(Chinese)",
    "Biáng biáng noodles - Chinese",
    "Calamarata",
    "Calamaretti",
    "Cannelloni",
    "Cavatappi",
    "Cellentani",
    "Chifferi",
    "Ditalini",
    "Fideuà",
    "Gomito",
    "Elicoidali",
    "Fagioloni",
    "Fusilli",
    "Garganelli",
    "Gemelli",
    "Maccheroncelli",
    "Maltagliati",
    "Manicotti",
    "Marziani",
    "Mezzani pasta",
    "Mezze penne",
    "Mezzi bombardoni",
    "Mostaccioli",
    "Paccheri",
    "Pasta al ceppo",
    "Penne",
    "Penne rigate",
    "Penne lisce",
    "Penne zita",
    "Pennette",
    "Pennoni",
    "Rigatoncini",
    "Rigatoni",
    "Sagne 'ncannulate",
    "Spirali",
    "Spiralini",
    "Trenne",
    "Trennette",
    "Tortiglioni",
    "Tuffoli",
    "Capunti",
    "Casarecce",
    "Cavatelli",
    "Cencioni",
    "Conchiglie",
    "Conchiglioni",
    "Corzetti",
    "Creste di galli",
    "Croxetti",
    "Farfalle",
    "Farfalloni",
    "Fiorentine",
    "Fiori",
    "Foglie d'ulivo",
    "Gigli",
    "Gramigna",
    "Lanterne",
    "Lumache",
    "Lumaconi",
    "Maltagliati",
    "Mandala",
    "Marille",
    "Orecchiette",
    "Pipe",
    "Quadrefiore",
    "Radiatori",
    "Ricciolini",
    "Ricciutelle",
    "Rotelle",
    "Rotini",
    "Strozzapreti",
    "Torchio",
    "Trofie",
    "Gnocchi",
    "Passatelli",
    "Spätzle",
    "Acini di pepe",
    "Bead-like pasta",
    "Alfabeto",
    "Anelli",
    "Anellini",
    "Couscous",
    "Conchigliette",
    "Corallini",
    "Ditali",
    "Ditalini",
    "Egg barley",
    "Farfalline",
    "Fideos",
    "Filini",
    "Fregula",
    "Funghini",
    "Israeli couscous",
    "Occhi di pernice",
    "Orzo (also, risoni)",
    "Pastina",
    "Pearl Pasta",
    "Ptitim",
    "Quadrettini",
    "Risi",
    "Seme di melone",
    "Stelle",
    "Stelline",
    "Stortini",
    "Tarhana",
    "Agnolotti",
    "Cannelloni",
    "Casoncelli or casonsèi",
    "Casunziei",
    "Fagottini",
    "Maultasche",
    "Mezzelune",
    "Occhi di lupo",
    "Pelmeni",
    "Pierogi",
    "Macaroni",
    "Ravioli",
    "Sacchettini",
    "Sacchettoni",
    "Tortellini",
    "Tortelloni",
    "Ramen"
]

var grains = [
    
    "Amaranth",
    "Barley",
    "Brown Rice",
    "Brown Rice Bread",
    "Brown Rice Tortilla",
    "Buckwheat",
    "Bulgur (Cracked Wheat)",
    "Farro / Emmer",
    "Flaxseed",
    "Grano",
    "Kamut® Grain",
    "Millet",
    "Oats",
    "Oat Bread",
    "Oat Cereal",
    "Oatmeal",
    "Popcorn",
    "Whole Wheat Cereal Flakes",
    "Muesli",
    "Rolled Oats",
    "Quinoa",
    "Rye",
    "Sorghum",
    "Spelt",
    "Teff",
    "Triticale",
    "Whole Grain Barley",
    "Wheat Berries",
    "Whole Grain Cornmeal",
    "Whole Rye",
    "Whole Wheat Bread",
    "Whole Wheat Couscous",
    "Whole Wheat Crackers",
    "Whole Wheat Pasta",
    "Whole Wheat Pita Bread",
    "Whole Wheat Sandwich Buns And Rolls",
    "Whole Wheat Tortillas",
    "Wild Rice",
    "White Rice",
    
]


var sides = [
    
    "Cornbread",
    "Corn Tortillas",
    "Couscous",
    "Flour Tortillas",
    "Grits",
    "Pitas",
    "Pretzels",
    "Naan"
 
]



// Pasta sauce?
