//
//  Produce.swift
//  Keep
//
//  Created by Luna An on 1/1/17.
//  Copyright © 2017 Mimicatcodes. All rights reserved.
//

import Foundation

var vegetables: [String] = [
    
    "Artichoke",
    "Arugula",
    "Asparagus",
    "Eggplant",
    "Amaranth",
    "Legumes",
    "Alfalfa Sprouts",
    "Azuki Beans",
    "Bean Sprouts",
    "Black Beans",
    "Black-eyed Peas",
    "Borlotti Bean",
    "Broad Beans",
    "Chickpeas",
    "Green Beans",
    "Kidney Beans",
    "Lentils",
    "Lima Beans",
    "Mung Beans",
    "Navy Beans",
    "Pinto Beans",
    "Runner Beans",
    "Split Beans",
    "Soy Beans",
    "Soy Bean Sprouts",
    "Peas",
    "Mangetout or Snap Peas",
    "Beet Greens",
    "Bok Choy",
    "Broccoflower",
    "Broccoli",
    "Brussels Sprouts",
    "Cabbage",
    "Calabrese",
    "Carrots",
    "Cauliflower",
    "Celery",
    "Chard",
    "Collard Greens",
    "Corn Salad",
    "Endive",
    "Fiddleheads",
    "Frisee",
    "Fennel",
    "Herbs and Spices",
    "Anise",
    "Basil",
    "Caraway",
    "Cilantro",
    "Coriander",
    "Chamomile",
    "Dill",
    "Fennel",
    "Lavender",
    "Lemon Grass",
    "Marjoram",
    "Oregano",
    "Parsley",
    "Rosemary",
    "Sage",
    "Thyme",
    "Kale",
    "Kohlrabi",
    "Lettuce",
    "Corn",
    "Mushrooms",
    "Mustard Greens",
    "Nettles",
    "New Zealand Spinach",
    "Napa Cabbage",
    "Okra",
    "Onion Family",
    "Chives",
    "Garlic",
    "Leek Allium Porrum",
    "Onion",
    "Shallot",
    "Green Onion",
    "Scallion",
    "Parsley",
    "Peppers",
    "Green Pepper",
    "Red Pepper",
    "Bell Pepper",
    "Chili Pepper",
    "Jalapeño",
    "Habanero",
    "Paprika",
    "Tabasco Pepper",
    "Cayenne Pepper",
    "Radicchio",
    "Rhubarb",
    "Root Vegetables",
    "Beet",
    "mangel-wurzel",
    "Carrot",
    "Celeriac",
    "Daikon",
    "Ginger",
    "Parsnip",
    "Rutabaga",
    "Turnip",
    "Radish",
    "Swede",
    "Rutabaga",
    "Turnip",
    "Wasabi",
    "Horseradish",
    "White Radish",
    "Salsify",
    "Skirret",
    "Spinach",
    "Topinambur",
    "Squashes",
    "Acorn Squash",
    "Butternut Squash",
    "Banana Squash",
    "Courgette",
    "Zucchini",
    "Cucumber",
    "Delicata",
    "Gem Squash",
    "Hubbard Squash",
    "Marrow",
    "Squash",
    "Patty Pans",
    "Pumpkin",
    "Spaghetti Squash",
    "Tat Soi",
    "Tomato",
    "Tubers",
    "Jicama",
    "Jerusalem Artichoke",
    "Potato",
    "Sunchokes",
    "Sweet Potato",
    "Taro",
    "Yam",
    "Turnip Greens",
    "Water Chestnut",
    "Watercress",
    "Zucchini",
    "String Beans",
    "Bamboo Shoots",
    "Snow Pea Shoots",
    "Chinese Broccoli"
]

var fruits: [String] = [
    
    "Apple",
    "Apricot",
    "Avocado",
    "Banana",
    "Bilberry",
    "Blackberry",
    "Blackcurrant",
    "Blueberry",
    "Boysenberry",
    "Currant",
    "Cherry",
    "Cherimoya",
    "Cloudberry",
    "Coconut",
    "Cranberry",
    "Cucumber",
    "Custard Apple",
    "Damson",
    "Date",
    "Dragonfruit",
    "Durian",
    "Elderberry",
    "Feijoa",
    "Fig",
    "Goji Berry",
    "Gooseberry",
    "Grape",
    "Raisin",
    "Grapefruit",
    "Guava",
    "Honeyberry",
    "Huckleberry",
    "Jabuticaba",
    "Jackfruit",
    "Jambul",
    "Jujube",
    "Juniper Berry",
    "Kiwi",
    "Kumquat",
    "Lemon",
    "Lime",
    "Loquat",
    "Longan",
    "Lychee",
    "Mango",
    "mangosteen",
    "Marionberry",
    "Melon",
    "Cantaloupe",
    "Honeydew",
    "Watermelon",
    "Miracle Fruit",
    "Mulberry",
    "Nectarine",
    "Nance",
    "Olive",
    "Orange",
    "Blood Orange",
    "Clementine",
    "Mandarine",
    "Tangerine",
    "Papaya",
    "Passionfruit",
    "Peach",
    "Pear",
    "Persimmon",
    "Physalis",
    "Plantain",
    "Plum",
    "Prune (dried plum)",
    "Pineapple",
    "Plumcot",
    "Pomegranate",
    "Pomelo",
    "Quince",
    "Raspberry",
    "Salmonberry",
    "Rambutan",
    "Redcurrant",
    "Salal Berry",
    "Salak",
    "Satsuma",
    "Star Fruit",
    "Strawberry",
    "Tamarillo",
    "Tamarind",
    "Tomato",
    "Ugli Fruit",
    "Yuzu",
    "Udara"
    
]


