//
//  Protein.swift
//  Keep
//
//  Created by Luna An on 3/6/17.
//  Copyright © 2017 Mimicatcodes. All rights reserved.
//

import Foundation

var meatsSeafoodsAndEggs: Set<String> = [

    "Sausage",
    "Beef",
    "Chicken",
    "Brown Eggs",
    "White Eggs",
    "Eggs",
    "Organic Eggs",
    "Free-range Eggs",
    "Cage-free Eggs",
    "Ground Turkey",
    "Ground Chicken",
    "Ham",
    "Pork",
    "Rabbit",
    "Goat",
    "Hot dogs",
    "Lunchmeat",
    "Turkey",
    "Pork",
    "Beef Steak",
    "Lamb",
    "Pork Chop",
    "Pork Cutlet",
    "Ground Beef",
    "Beef Chuck",
    "Beef Shank",
    "Beef Brisket",
    "Beef Rib",
    "Beef Short Plate",
    "Beef Flank",
    "Beef Loin",
    "Beef Sirloin",
    "Beef The round",
    "Beef Tongue",
    "Beef Neck",
    "Beef Knuckle",
    "Pork Back Ribs",
    "Pork Bacon",
    "Pork Belly",
    "Pork Steak ",
    "Pork Country-style Ribs",
    "Pork Crown Roast",
    "Pork Cubed and Sliced",
    "Ground Pork",
    "Pork Ham",
    "Pork Loin Roast",
    "Pork Pork Chops",
    "Pork Brisket",
    "Pork Sausage",
    "Pork Shoulder",
    "Pork Spareribs",
    "Pork Tenderloin",
    "Fish",
    "Tuna",
    "Crab",
    "Fish Fillets",
    "Fish Steaks",
    "Fish Whole",
    "Lobster",
    "Mussels",
    "Clams",
    "Oysters",
    "Salmon",
    "Scallops",
    "Shrimp",
    "Prepped Fish",
    "Prepped Shellfish"
]

var beansPeasAndTofu: Set<String> = [
    "Azuki Beans",
    "Black Beans",
    "Baked Beans",
    "Black-eyed Peas",
    "Borlotti Bean",
    "Broad Beans",
    "Canned Beans",
    "Chickpeas",
    "Green Beans",
    "Kidney Beans",
    "Lentils",
    "Lima Beans",
    "Mung Beans",
    "Navy Beans",
    "Pinto Beans",
    "Runner Beans",
    "Split Beans",
    "Soy Beans",
    "Peas",
    "Mangetout/Snap Peas",
     "Tofu"
    
]

var nutsAndSeeds: Set<String> = [
    "Almond",
    "Australian Nut",
    "Beech",
    "Black Walnut",
    "Blanched Almond",
    "Brazil Nut",
    "Butternut",
    "Candle Nut",
    "Candlenut",
    "Cashew",
    "Chestnuts",
    "Chinese Almond",
    "Chinese Chestnut",
    "Chinkapin",
    "Chufa Nut",
    "Cobnut",
    "Colocynth",
    "Country Walnut",
    "Cream Nut",
    "Cucurbita Ficifolia",
    "Earth Almond",
    "Earth Nut",
    "English Walnuts",
    "Filbert",
    "Florida Almond",
    "Gevuina Avellana",
    "Gingko Nut",
    "Hazelnut",
    "Heartnut",
    "Hickory Nut",
    "Horned Water Chestnut",
    "Indian Beech",
    "Indian Nut",
    "Japanese Walnut",
    "Java Almond",
    "Jesuit Nut",
    "Juniper Berry",
    "Kluwak Nuts",
    "Kola Nut",
    "Macadamia",
    "Malabar Chestnut",
    "Mamoncillo",
    "Maya Nut",
    "Mongongo",
    "Oak Acorns",
    "Ogbono Nut",
    "Para Nut",
    "Paradise Nut",
    "Pecan",
    "Persian Walnuts",
    "Pili Nut",
    "Pine Nut",
    "Pine Nut",
    "Pinyon",
    "Pistachio Nut",
    "Pistacia",
    "Polynesian Chestnut",
    "Queensland Nut",
    "Royal Walnuts",
    "Rush Nut",
    "Sapucaya Nut",
    "Sapucia Nut",
    "Shagbark Hickory",
    "Sliced Almonds",
    "Slivered Almond",
    "Sweet Almond",
    "Sweet Chestnut",
    "Terminalia Catappa",
    "Tiger Nut",
    "Walnut",
    "Water Caltrop",
    "White Nut",
    "White Walnut",
    "Chia seeds",
    "Flaxseed",
    "Hemp seeds",
    "Poppy seed",
    "Pumpkin seeds",
    "Sesame seed",
    "Safflower",
    "Sunflower"
]

