//
//  File.swift
//  Keep
//
//  Created by Luna An on 1/1/17.
//  Copyright © 2017 Mimicatcodes. All rights reserved.
//

import Foundation

var vegetables: [String] = [
    
    "Artichoke",
    "Arugula",
    "Asparagus",
    "Eggplant",
    "Amaranth",
    "Legumes",
    "Alfalfa sprouts",
    "Azuki beans",
    "Bean sprouts",
    "Black beans",
    "Black-eyed peas",
    "Borlotti bean",
    "Broad beans",
    "Chickpeas",
    "Green beans",
    "Kidney bean",
    "Lentils",
    "Lima beans",
    "Mung beans",
    "Navy beans",
    "Pinto beans",
    "Runner beans",
    "Split peas",
    "Soy beans",
    "Soy bean sprouts",
    "Peas",
    "Mangetout or Snap peas",
    "Beet greens",
    "Bok choy",
    "Broccoflower",
    "Broccoli",
    "Brussels sprouts",
    "Cabbage",
    "Calabrese",
    "Carrots",
    "Cauliflower",
    "Celery",
    "Chard",
    "Collard greens",
    "Corn salad",
    "Endive",
    "Fiddleheads",
    "Frisee",
    "Fennel",
    "Herbs and spices",
    "Anise",
    "Basil",
    "Caraway",
    "Cilantro",
    "Coriander",
    "Chamomile",
    "Dill",
    "Fennel",
    "Lavender",
    "Lemon Grass",
    "Marjoram",
    "Oregano",
    "Parsley",
    "Rosemary",
    "Sage",
    "Thyme",
    "Kale",
    "Kohlrabi",
    "Lettuce",
    "Corn",
    "Mushrooms",
    "Mustard greens",
    "Nettles",
    "New Zealand spinach",
    "Napa Cabbage",
    "Okra",
    "Onion family",
    "Chives",
    "Garlic",
    "Leek Allium porrum",
    "Onion",
    "Shallot",
    "Green onion",
    "Scallion",
    "Parsley",
    "Peppers",
    "Green pepper",
    "Red pepper",
    "Bell pepper",
    "Chili pepper",
    "Jalapeño",
    "Habanero",
    "Paprika",
    "Tabasco pepper",
    "Cayenne pepper",
    "Radicchio",
    "Rhubarb",
    "Root vegetables",
    "Beet",
    "mangel-wurzel",
    "Carrot",
    "Celeriac",
    "Daikon",
    "Ginger",
    "Parsnip",
    "Rutabaga",
    "Turnip",
    "Radish",
    "Swede",
    "Rutabaga",
    "Turnip",
    "Wasabi",
    "Horseradish",
    "White radish",
    "Salsify",
    "Skirret",
    "Spinach",
    "Topinambur",
    "Squashes",
    "Acorn squash",
    "Butternut squash",
    "Banana squash",
    "Courgette",
    "Zucchini",
    "Cucumber",
    "Delicata",
    "Gem squash",
    "Hubbard squash",
    "Marrow",
    "Squash",
    "Patty pans",
    "Pumpkin",
    "Spaghetti squash",
    "Tat soi",
    "Tomato",
    "Tubers",
    "Jicama",
    "Jerusalem artichoke",
    "Potato",
    "Sunchokes",
    "Sweet potato",
    "Taro",
    "Yam",
    "Turnip greens",
    "Water chestnut",
    "Watercress",
    "Zucchini"
]
