//
//  Vegetables.swift
//  Keep
//
//  Created by Luna An on 3/6/17.
//  Copyright © 2017 Mimicatcodes. All rights reserved.
//

import Foundation

var vegetables: Set<String> = [
    
    "Artichoke",
    "Arugula",
    "Asparagus",
    "Eggplant",
    "Amaranth",
    "Legumes",
    "Alfalfa Sprouts",
    "Bean Sprouts",
    "Soy Bean Sprouts",
    "Beet Greens",
    "Bok Choy",
    "Broccoflower",
    "Broccoli",
    "Brussels Sprouts",
    "Canned Vegetables",
    "Cabbage",
    "Calabrese",
    "Carrots",
    "Cauliflower",
    "Celery",
    "Chard",
    "Collard Greens",
    "Corn Salad",
    "Endive",
    "Fiddleheads",
    "Frisee",
    "Fennel",
    "Herbs and Spices",
    "Anise",
    "Basil",
    "Caraway",
    "Cilantro",
    "Coriander",
    "Chamomile",
    "Dill",
    "Fennel",
    "Lavender",
    "Lemon Grass",
    "Marjoram",
    "Oregano",
    "Parsley",
    "Rosemary",
    "Sage",
    "Thyme",
    "Kale",
    "Kohlrabi",
    "Lettuce",
    "Corn",
    "Mushrooms",
    "Mustard Greens",
    "Nettles",
    "New Zealand Spinach",
    "Napa Cabbage",
    "Okra",
    "Onion Family",
    "Chives",
    "Garlic",
    "Leek Allium Porrum",
    "Onion",
    "Shallot",
    "Green Onion",
    "Scallion",
    "Parsley",
    "Peppers",
    "Green Pepper",
    "Red Pepper",
    "Bell Pepper",
    "Chili Pepper",
    "Jalapeño",
    "Habanero",
    "Paprika",
    "Tabasco Pepper",
    "Cayenne Pepper",
    "Radicchio",
    "Rhubarb",
    "Root Vegetables",
    "Beet",
    "mangel-wurzel",
    "Carrot",
    "Celeriac",
    "Daikon",
    "Ginger",
    "Parsnip",
    "Rutabaga",
    "Turnip",
    "Radish",
    "Swede",
    "Rutabaga",
    "Turnip",
    "Wasabi",
    "Horseradish",
    "White Radish",
    "Salsify",
    "Skirret",
    "Spinach",
    "Topinambur",
    "Squashes",
    "Acorn Squash",
    "Butternut Squash",
    "Banana Squash",
    "Courgette",
    "Zucchini",
    "Cucumber",
    "Delicata",
    "Gem Squash",
    "Hubbard Squash",
    "Marrow",
    "Squash",
    "Patty Pans",
    "Pumpkin",
    "Spaghetti Squash",
    "Tat Soi",
    "Tomato",
    "Tubers",
    "Jicama",
    "Jerusalem Artichoke",
    "Potato",
    "Sunchokes",
    "Sweet Potato",
    "Taro",
    "Yam",
    "Turnip Greens",
    "Water Chestnut",
    "Watercress",
    "Zucchini",
    "String Beans",
    "Bamboo Shoots",
    "Snow Pea Shoots",
    "Chinese Broccoli"
]
